language: python
python:
  - "2.7"
sudo: false
virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
     - python-pygame
install: "pip install -r requirements.txt"
script: "py.test"
