language: python
python:
  - "2.6"
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
	"sudo apt-get install python-pygame -y"
install: "pip install -r requirements.txt"
script: "py.test"
